spring:
  redis:
    host: 127.0.0.1
    port: 6379


server:
  port: 9001
#  servlet:
#    session:
#      cookie:
#        path=/
  reactive:
    session:
      timeout: 30m
#设置Spring session 的session声明周期为30m表示30分钟默认为30m
#server.servlet.session.timeout=30m
#指定Cookie的存放路径为根路径用于实现同域名不同项目的session共享
#server:
#  servlet:
#    session:
#      cookie:
#        path=/
#指定cookie的存域名用于实现同根域名不同二级子域名的Session共享
#server.servlet.session. cookie.domain=myweb. com